server:
  port: 8080
  contextPath:  /
# JWT
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  tokenHead: "Bearer "
  route:
    authentication:
      path: "powerplant/auth"
      refresh: "powerplant/auth/refresh"
      register: "powerplant/auth/register"
    user:
      path: "powerplant/user"
    role:
      path: "powerplant/role"
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
      dialect:  org.hibernate.dialect.PostgreSQLDialect
  primary:
    datasource:
      driverClassName: org.postgresql.Driver
      url:  jdbc:postgresql://localhost:5432/db1
      username: powerplant
      password: powerplant
  secondary:
    datasource:
      driverClassName: org.postgresql.Driver
      url:  jdbc:postgresql://localhost:5432/db2
      username: powerplant
      password: powerplant



logging:
  level:
    org.springframework.web: DEBUG
    com.github.binarywang.demo.wechat: DEBUG
