spring:
  profiles:
    active: DB, dev
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  freemarker:
    prefix:
    suffix:  .ftl
    template-loader-path: classpath:/templates
logging:
  level:
    root: info

