spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://115.29.106.186:3306/test?serverTimezone=UTC&useSSL=false
    username: gan
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true



