server:
   port: 8081
spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.DriverSpy
    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/yorozuya?serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
###########
#自定义属性#
###########

#文件上传路径
file:
  path: /Users/zhangjin/IdeaProjects/myself/yorozuya/MP/src/main/resources/file
  type: .md