spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  freemarker:
    prefix:
    suffix:  .ftl
    template-loader-path: classpath:/templates
logging:
  level:
    root: info

jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  tokenHead: "Bearer "
  route:
    authentication:
      path: "auth"
      refresh: "auth/refresh"
      register: "auth/register"
    user:
      path: "user"
    role:
      path: "role"
