spring:
#  mvc:
#    view:
#      prefix: classpath:/templates/
#      suffix: .ftl
#  thymeleaf:
#    prefix: classpath:/templates/
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true



