spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.DriverSpy
    url: jdbc:log4jdbc:mysql://115.29.106.186:3306/test?serverTimezone=UTC&useSSL=false
    username: gan
    password: 123456
    data: classpath:db/*.sql
